name: test-deploy
reference: refs/heads/main
working_dir: test
compose_files:
  - test.compose.yaml
---
name: test-deploy-2
reference: refs/heads/main
working_dir: test
compose_files:
  - test.compose.yaml
