services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    environment:
      TZ: Europe/Berlin
      HTTP_PORT: 80
      LOG_LEVEL: debug
      GITHUB_WEBHOOK_SECRET: bdfv8y!oghvi4ea3b-5tiehrefgdnb
      DEPLOYMENT_CONFIG_FILE_NAME: /.compose-webhook.y(a)?ml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock