# NOTE: This is just for testing deployments
services:
  app:
    container_name: test2
    image: nginx:latest
    ports:
      - "8089:80"  # use random published port
    volumes:
      - ./:/usr/share/nginx/html
